### ISSUE TITLE
History gone?

### ISSUE THREAD

**Issue by tontonsb** [folkloreinc/laravel-image#1]
Was whole git history rewritten here? We were cloning particular commit from the v1.1.x-dev branch and it seems gone now.

**Comment by dmongeau** [comment]
You might want to use https://github.com/folkloreinc/laravel-image-legacy/tree/v1.1

**Comment by tontonsb** [comment]
Thanks! A legacy copy was exactly what I was hoping for when making this issue. I just didn't find the repo myself :)
